name: On Release Published

on:
  release:
    types: [published]

jobs:
  pkg-binaries:
    timeout-minutes: 10
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.17.0'

    - name: Installing root deps
      run: npm ci

    - name: Installing backend deps
      run: npm ci
      working-directory: backend

    - name: Installing frontend deps
      run: npm ci
      working-directory: frontend

    - name: Building FE bundle
      run: npm run build
    
    - name: Bulding pkg
      run: npx pkg .
      working-directory: backend
    
    - name: Zip builds
      run: |
        cd dist
        zip -r teevittie-linux.zip teevittie-linux
        zip -r teevittie-macos.zip teevittie-macos
        zip -r teevittie-win.zip teevittie-win.exe
      working-directory: backend

    - name: Upload Linux Bin
      uses: djn24/add-asset-to-release@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        path: 'backend/dist/teevittie-linux.zip'

    - name: Upload MacOS Bin
      uses: djn24/add-asset-to-release@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        path: 'backend/dist/teevittie-macos.zip'

    - name: Upload Win Bin
      uses: djn24/add-asset-to-release@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        path: 'backend/dist/teevittie-win.zip'

    - name: Zip Bundled Source 
      run: |
        rm -rf node_modules bin tests nodemon.json tmp dist scripts
        cd .. && mv backend teevittie-src
        zip -r teevittie-source.zip teevittie-src
      working-directory: backend

    - name: Upload Bundled Source
      uses: djn24/add-asset-to-release@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        path: 'teevittie-source.zip'